### ISSUE TITLE
How to extract update.rpf and recreate ?

### ISSUE THREAD

**Issue by shamim4s** [indilo53/gtautil#38] opened 2023-10-09 12:00 UTC
Hi, 
I have tried to unpack update.rpf file and just repack update.rpf for test. But my game crash when I use new update.rpf file.
I used these 3 steps
gtautil extractarchive --input update.rpf --output update

gtautil createarchive --input update --output updatenew --name update

gtautil fixarchive --input updatenew\update.rpf --recursive

It's create update.rpf file but game crash if I use that rpf

How can I do that please?

**Comment by gizzdev** [comment] 2023-10-11 14:55
This may be caused by this resolved issue : https://github.com/indilo53/gtautil/issues/38

Here is new repo : https://github.com/gizzdev/gtautil

**Comment by shamim4s** [comment] 2023-10-11 21:24
Hi, Thanks for your reply. i have downloaded gizzdev/gtautil new version, but still failed.
my game version is 1.0.2944.0, first i build cache by run both command .
gtautil buildcache
gtautil gencache

then i have tried in two way,
first way:
1. gtautil extractarchive --input "..\Grand Theft Auto V\mods\update\update.rpf" --output newupdate
"then moved original update.rpf file to backup"

2.gtautil createarchive --input output --newupdate "..\Grand Theft Auto V\mods\update" --name update
"its create a update.rpf done"

3.gtautil fixarchive --input "../Grand Theft Auto V/mods/update/update.rpf" --recursive
"its return skip update.rpf at the last line." screenshot no 1.
in this way, game gives "err_mem_embeddedalloc_alloc" . i have tried "PackfileLimitAdjuster", "HeapAdjuster", "PoolManager","gameconfig.xml" all patchs, but no luck :(
![gtautil-1 jpg](https://github.com/indilo53/gtautil/assets/85999549/5c9af5c8-e10a-4093-b694-bf6548b4a311)

second way:
i have extract update.rpf data from openiv then did (step 2 & step 3) again 
"its return ENCRYPT update.rpf at the last line." screenshot no 2.
in this way, game gives "err_gameconfig_1" . i have tried different type of "gameconfig.xml" files, but still no luck :(
![gtautil-2](https://github.com/indilo53/gtautil/assets/85999549/19025625-112a-45a8-bc17-80899a2f4001)


is there anything i'm missing??
please advice me how to do it.

Best regards
Shamim

**Comment by gizzdev** [comment] 2023-10-12 10:56
[gtautil-0.0.0.zip](https://github.com/indilo53/gtautil/files/12880580/gtautil-0.0.0.zip)

Hello, try this release and let me know how is it going.

No need to fix archive when generated via createarchive.

## You need to extractarchive again
## You also need to createarchive again

Both implementations were wrong.

**Comment by shamim4s** [comment] 2023-10-12 18:44
> [gtautil-0.0.0.zip](https://github.com/indilo53/gtautil/files/12880580/gtautil-0.0.0.zip)
> 
> Hello, try this release and let me know how is it going.
> 
> No need to fix archive when generated via createarchive.
> 
> ## You need to extractarchive again
> ## You also need to createarchive again
> Both implementations were wrong.

yes this version is working fine.. Thanks for your support. :)

**Comment by gizzdev** [comment] 2023-10-12 19:49
Nice, so I can close the issue and releasing it !

**Closed as completed** 2023-10-12 19:50 UTC
